# Generated by Django 4.2.7 on 2025-10-25 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_number', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Camera Statuses',
                'ordering': ['camera_number'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('uploaded_image', models.ImageField(upload_to='known_faces/')),
                ('face_embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('camera_number', models.IntegerField()),
                ('detection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='detections/')),
            ],
            options={
                'ordering': ['-detection_time'],
                'indexes': [models.Index(fields=['-detection_time'], name='recognition_detecti_405d31_idx'), models.Index(fields=['person_name'], name='recognition_person__269a17_idx'), models.Index(fields=['camera_number'], name='recognition_camera__ece2d2_idx')],
            },
        ),
    ]
